// vue-js/src/components/conferences/ConferenceDetails.vue
<template>
  <div class="section">
    <div class="container">
      <div class="columns">
        <div class="column">
          <cp-conference-details-header
            :attendeesCount="conference.attendeesCount.count"
            :sponsorsCount="conference.sponsorsCount.count"
            :speakersCount="conference.speakerCount"
          >
          </cp-conference-details-header>
          <p class="title is-3 has-text-muted">
            <!--Conference description-->
            {{conference.description}}
          </p>
          <hr>
          <br>
          <p class="title is-4">
            Talks :
          </p>
          <!--Conference talks-->

          <div class="columns" v-for="talks in talkChunk">
            <div class="column is-6" v-for="talk in talks">
              <cp-talk-card
                :talk="talk"
              ></cp-talk-card>
            </div>
          </div>
          <hr>

          <p class="title is-4">
            Speakers :
          </p>

          <!--Conference Speakers-->
          <div class="columns" v-for="speakersChunk in speakerChunk">
            <div class="column is-6" v-for="speaker in speakersChunk">
              <cp-speaker-card
                :speaker="speaker"
              ></cp-speaker-card>
            </div>
          </div>
          <hr>
          <!--Conference sponsors-->
          <p class="title is-4 is-spaced">
            Sponsors :
          </p>
          <!--Conference sponsors : GOLD-->
          <p class="subtitle is-5">GOLD</p>
          <cp-sponsor-box
            v-for="sponsor in conference.goldSponsors"
            key="$index"
            :picture="sponsor.entreprise.logo"
            :name="sponsor.entreprise.name"
            :description="sponsor.entreprise.description"
          >
          </cp-sponsor-box>

          <br>
          <!--Conference sponsors : SILVER-->
          <p class="subtitle is-5">SILVER</p>
          <cp-sponsor-box
            v-for="sponsor in conference.silverSponsors"
            key="$index"
            :picture="sponsor.entreprise.logo"
            :name="sponsor.entreprise.name"
            :description="sponsor.entreprise.description"
          >
          </cp-sponsor-box>
          <br>
          <!--Conference sponsors : BRONZE-->
          <p class="subtitle is-5">BRONZE</p>
          <cp-sponsor-box
            v-for="sponsor in conference.bronzeSponsors"
            key="$index"
            :picture="sponsor.entreprise.logo"
            :name="sponsor.entreprise.name"
            :description="sponsor.entreprise.description"
          >
          </cp-sponsor-box>
          <br>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
  import {split} from '../../utils';
  import ConferenceDetailsHeader from './ConferenceDetailsHeader';
  import TalkCard from '../talk/TalkCard.vue';
  import SpeakerCard from '../speaker/SpeakerCard.vue';
  import SponsorBox from '../shared/SponsorBox.vue';
  import {DetailedConferenceQuery} from './conference.apollo-query';

  export default {
    name: 'cp-conference-details',
    data() {
      return {
        conference: {
          talks: [],
          speakers: [],
          attendeesCount: {},
          sponsorsCount: {},
          goldSponsors: []
        }
      };
    },
    computed: {
      talkChunk: function () {
        return split(2, this.conference.talks)
      },
      speakerChunk: function () {
        return split(2, this.conference.speakers)
      }
    },
    apollo: {
      // TODO: Write DetailedConferenceQuery
    },
    components: {
      'cp-conference-details-header': ConferenceDetailsHeader,
      'cp-talk-card': TalkCard,
      'cp-speaker-card': SpeakerCard,
      'cp-sponsor-box': SponsorBox
    },
  }
</script>

// angular/src/app/conference/conference-details/conference-details.component.ts
import {Component, OnDestroy, OnInit} from '@angular/core';
import {Conference} from '../types';
import {Apollo} from 'apollo-angular';
import {DetailedConferenceQuery, DetailedConferenceQueryResponse} from '../conference.apollo-query';
import {ActivatedRoute, ParamMap} from '@angular/router';
import {Subscription} from 'rxjs/Subscription';
import 'rxjs/add/operator/switchMap';
import 'rxjs/add/operator/map';
import {chunk, unsubscribeAll} from '../../utils';
import {Observable} from 'rxjs/Observable';
import 'rxjs/add/observable/empty';

@Component({
  selector: 'cp-conference-details',
  templateUrl: './conference-details.component.html',
  styles: []
})
export class ConferenceDetailsComponent implements OnInit, OnDestroy {
  loading: boolean;
  conference: Conference;

  subscriptions: Subscription[] = [];

  constructor(private route: ActivatedRoute) {
    this.getConferenceDetails = this.getConferenceDetails.bind(this);
  }

  ngOnInit() {
    this.subscriptions = this.subscriptions.concat(
      this.route.paramMap
        .map((params: ParamMap) => params.get('id'))
        .switchMap(this.getConferenceDetails)
        .subscribe(res => {
          //Get the data from graphQL
          //Loading and conference.
          //You should calculate speakerCount,
          //Use the chunk util on talks and speakers to create columns and rows appropriately
        })
    );
  }

  getConferenceDetails(conferenceId: String) {
    //TODO  call the graphQL query with apollo
    //The query is in conference.apollo-query.ts
    return Observable.empty();
  }


  ngOnDestroy(): void {
    unsubscribeAll(this.subscriptions);
  }
}

<cp-page-header
  [headers]="[conference?.name, conference?.city]"
></cp-page-header>
<div class="section">
  <div class="container">
    <div class="columns">
      <div class="column">
        <cp-conference-details-level
          [attendeesCount]="conference?.attendeesCount?.count || 0"
          [sponsorsCount]="conference?.sponsorsCount?.count || 0"
          [speakersCount]="conference?.speakerCount"
        ></cp-conference-details-level>
        <p class="title is-3 has-text-muted">
          <!--Conference description-->
          {{conference?.description}}
        </p>
        <hr>
        <br>
        <p class="title is-4">
          Talks :
        </p>
        <!--Conference talks-->

        <div class="columns" *ngFor="let talkChunks of conference?.talks">
          <div class="column is-6" *ngFor="let talk of talkChunks">
            <cp-talk-card
              [talk]="talk"
            ></cp-talk-card>
          </div>
        </div>
        <hr>

        <p class="title is-4">
          Speakers :
        </p>

        <!--Conference Speakers-->
        <div class="columns" *ngFor="let speakersChunk of conference?.speakers">
          <div class="column is-6" *ngFor="let speaker of speakersChunk">
            <cp-speaker-card
              [speaker]="speaker"
            ></cp-speaker-card>
          </div>
        </div>
        <hr>
        <!--Conference sponsors-->
        <p class="title is-4 is-spaced">
          Sponsors :
        </p>
        <!--Conference sponsors : GOLD-->
        <p class="subtitle is-5">GOLD</p>
        <cp-sponsor-box
          *ngFor="let sponsor of conference?.goldSponsors"
          [picture]="sponsor.entreprise?.logo"
          [name]="sponsor.entreprise?.name"
          [description]="sponsor.entreprise?.description"
        ></cp-sponsor-box>
        <br>
        <!--Conference sponsors : SILVER-->
        <p class="subtitle is-5">SILVER</p>
        <cp-sponsor-box
          *ngFor="let sponsor of conference?.silverSponsors"
          [picture]="sponsor.entreprise?.logo"
          [name]="sponsor.entreprise?.name"
          [description]="sponsor.entreprise?.description"
        ></cp-sponsor-box>
        <br>
        <!--Conference sponsors : BRONZE-->
        <p class="subtitle is-5">BRONZE</p>
        <cp-sponsor-box
          *ngFor="let sponsor of conference?.bronzeSponsors"
          [picture]="sponsor.entreprise?.logo"
          [name]="sponsor.entreprise?.name"
          [description]="sponsor.entreprise?.description"
        ></cp-sponsor-box>
        <br>
      </div>
    </div>
  </div>
</div>
