// vue-js/src/components/speaker/SpeakerDetails.vue
<template>
  <div>
    <div class="section">
      <div class="container">
        <div class="columns">
          <div class="column">
            <p class="title is-3 has-text-muted">
              {{speaker.bio}}
            </p>
            <hr/>
            <p class="title is-4">
              Talks :
            </p>

            <div class="columns" v-for="talks in chunkTalks">
              <div class="column is-6" v-for="talk in talks">
                <cp-talk-card
                  :talk="talk"
                >
                </cp-talk-card>
              </div>
            </div>

          </div>
        </div>
      </div>
    </div>
  </div>

</template>

<script>
  import {getSpeakerById} from './speaker.apollo-query';
  import {split} from '../../utils';
  import TalkCard from '../talk/TalkCard.vue';

  export default {
    name: 'SpeakerDetails',
    data() {
      return {
        speaker: {}
      };
    },
    computed: {
      chunkTalks() {
        return split(3, this.speaker.talks);
      }
    },
    apollo: {
      // TODO: Write getSpeakerById
    },
    components: {
      'cp-talk-card': TalkCard
    }
  }
</script>

// angular/src/app/speaker/speaker-details/speaker-details.component.ts
import {Component, OnDestroy, OnInit} from "@angular/core";
import {ActivatedRoute, ParamMap} from '@angular/router';
import {getSpeakerByIdResponse} from '../speaker.apollo-query';
import {chunk, unsubscribeAll} from '../../utils';
import {Subscription} from 'rxjs/Subscription';
import {Speaker} from '../types';
import {Observable} from 'rxjs/Observable';
import 'rxjs/add/observable/empty';

@Component({
  selector: 'cp-speaker-details',
  templateUrl: './speaker-details.component.html'
})
export class SpeakerDetailsComponent implements OnInit, OnDestroy {

  speaker: Speaker;
  loading;
  subscriptions: Subscription[] = [];

  constructor(private route: ActivatedRoute) {
    this.getSpeaker = this.getSpeaker.bind(this);
  }

  ngOnInit() {
    const getSpeaker$ = this.route.paramMap
      .map((params: ParamMap) => params.get('id'))
      .switchMap(this.getSpeaker)
      .subscribe(({ data }) => {
        this.loading = data.loading;
        this.speaker = this.updateSpeaker(data);
      });

    this.subscriptions = this.subscriptions.concat(getSpeaker$);
  }

  getSpeaker(speakerId: string) {
    // TODO: Write getSpeakerById and execute it
    return Observable.empty();
  }

  updateSpeaker(data: getSpeakerByIdResponse): Speaker {
    return Object.assign({},
      ...data.speaker,
      {
        talks: chunk(data.speaker.talks, 2)
      }
    );
  }


  ngOnDestroy(): void {
    unsubscribeAll(this.subscriptions);
  }
}

<div>
  <cp-page-header
    [headers]="[speaker?.username, '@' + speaker?.publicName]"
    [pipe]="false"
  ></cp-page-header>
  <div class="section">
    <div class="container">
      <div class="columns">
        <div class="column">
          <p class="title is-3 has-text-muted">
            {{speaker?.bio}}
          </p>
          <hr/>
          <p class="title is-4">
            Talks :
          </p>

          <div class="columns" *ngFor="let chunkTalks of speaker?.talks">
            <div class="column is-6" *ngFor="let talk of chunkTalks">
              <cp-talk-card
                [talk]="talk"
              >
              </cp-talk-card>
            </div>
          </div>

        </div>
      </div>
    </div>
  </div>
</div>
