// vue-js/src/components/authentication/Login.vue
<template>
  <form class="container" novalidate>
    <div class="columns is-vcentered">
      <div class="column is-4 is-offset-4">
        <h1 class="title">
          Sign in
        </h1>
        <div class="box">
          <label class="label">Email*</label>
          <p class="control">

            <input
              class="input"
              :class="{
                'is-danger':$v.credentials.email.$invalid && $v.credentials.email.$dirty
              }"
              type="email"
              placeholder="jsmith@example.org"
              @blur="$v.credentials.email.$touch()"
              v-model="credentials.email"
              required
            />
          </p>
          <label class="label">Password*</label>
          <p class="control">
            <input
              class="input"
              :class="{
                'is-danger':$v.credentials.password.$invalid && $v.credentials.password.$dirty
              }"
              type="password"
              placeholder="●●●●●●●"
              @blur="$v.credentials.password.$touch()"
              v-model="credentials.password"
              required
            />
          </p>

          <p v-if="userNotFound">
            User not found
          </p>

          <hr/>

          <p class="control">
            <button class="button is-outlined is-large is-fullwidth"
                    @click.prevent="login()" :disabled="$v.$invalid">
              Login
            </button>
          </p>
        </div>
        <p class="has-text-centered">
          <router-link to="/authentication/register" active-class="is-active">
            Register
          </router-link>
        </p>
      </div>
    </div>
  </form>

</template>
<script>
  import {login} from './authentication.apollo-query';
  import {required, email, minLength, maxLength, between} from 'vuelidate/lib/validators'
  import auth from './authentication.service';

  export default {
    data() {
      return {
        userNotFound: false,
        publicName: '',
        credentials: {
          email: '',
          password: '',
        }
      }
    },
    validations: {
      credentials: {
        email: {
          required,
          email,
          maxLength: maxLength(50),
        },
        password: {
          required,
          maxLength: maxLength(50),
          minLength: minLength(3),
        }
      }
    },
    apollo: {},
    methods: {
      login() {
        // TODO: Write login mutation and execute it
        // Replace Promise.reject() by the correct call
        Promise.reject()
          .then(({data}) => {
            this.userNotFound = false;
            this.publicName = data.signinUser.user.publicName;
            this.storePublicNameInLocalStorage(this.publicName);
            this.navigateToHome();
          })
          .catch((error) => {
            console.log(error);
            this.userNotFound = true;
          })
      },
      storePublicNameInLocalStorage(name) {
        auth.savePublicName(name);
      },
      navigateToHome() {
        this.$router.push('/');
      }
    }
  }
</script>

// angular/src/app/authentication/login/login.component.ts
import {Component, OnDestroy, OnInit} from '@angular/core';
import {FormBuilder, FormGroup, Validators} from '@angular/forms';
import {Subscription} from 'rxjs/Subscription';
import {unsubscribeAll} from '../../utils';
import {Router} from '@angular/router';
import {Observable} from 'rxjs/Observable';
import 'rxjs/add/observable/empty';

@Component({
  selector: 'cp-login-component',
  templateUrl: './login.component.html'
})
export class LoginComponent implements OnInit, OnDestroy {

  userNotFound = false;
  publicName: string;
  loginForm: FormGroup;

  subscriptions: Subscription[] = [];

  constructor(private fb: FormBuilder, private router: Router) {
  }

  ngOnInit(): void {
    this.loginForm = this.fb.group({
      email: ['', [Validators.required, Validators.email, Validators.maxLength(50)]],
      password: ['', [Validators.required, Validators.minLength(3), Validators.maxLength(50)]]
    });
  }

  login(values: { email: string, password: string }) {

    // TODO: Write LoginMutation and execute it
    const loginMutation$ = Observable.empty()
      .subscribe(({ data }) => {
        this.userNotFound = false;
        this.publicName = data.signinUser.user.publicName;
        this.storePublicNameInLocalStorage(this.publicName);
        this.navigateToHome();
      }, error => {
        this.userNotFound = true;
      });

    this.subscriptions = this.subscriptions.concat(loginMutation$);
  }

  storePublicNameInLocalStorage(name: string) {
    localStorage.setItem('cp-public-name', name);
  }

  navigateToHome() {
    this.router.navigate(['/']);
  }


  ngOnDestroy(): void {
    unsubscribeAll(this.subscriptions);
  }
}

<form
  [formGroup]="loginForm"
  class="container"
  novalidate
>
  <div class="columns is-vcentered">
    <div class="column is-4 is-offset-4">
      <h1 class="title">
        Sign in
      </h1>
      <div class="box">
        <label class="label">Email*</label>
        <p class="control">

          <input
            class="input"
            [class.is-danger]="loginForm.get('email').invalid && loginForm.get('email').dirty"
            type="email"
            placeholder="jsmith@example.org"
            formControlName="email"
            required
          />
        </p>
        <label class="label">Password*</label>
        <p class="control">
          <input
            class="input"
            [class.is-danger]="loginForm.get('password').invalid && loginForm.get('password').dirty"
            type="password"
            placeholder="●●●●●●●"
            formControlName="password"
            required
          />
        </p>

        <p *ngIf="userNotFound" class="is-danger">
          User not found
        </p>

        <hr/>

        <p class="control">
          <button
            class="button is-outlined is-large is-fullwidth"
            [class.is-danger]="loginForm.invalid"
            [class.is-info]="loginForm.valid"
            [disabled]="loginForm.invalid "
            (click)="login(loginForm.getRawValue())"
          >Login
          </button>
        </p>
      </div>
      <p class="has-text-centered">
        <a routerLink="/authentication/register">Register</a>
      </p>
    </div>
  </div>
</form>
