// vue-js/src/components/management/talks/TalkForm.vue
<template>
  <div>
    <cp-page-header
      :headers="['Talks', 'Management', this.idParam ? 'Update' : 'Add']"
    >
    </cp-page-header>

    <cp-success-modal
      title="Success"
      subTitle=""
      :isVisible="showModalSuccess"
      :on-close="onClose"
      :text="successModalText">
    </cp-success-modal>

    <form
      novalidate
      class="section">
      <div class="container">
        <div class="columns">
          <div class="column">
            <div class="field">
              <label class="label">Title*</label>
              <p class="control">
                <input
                  class="input"
                  :class="{
                    'is-danger':$v.talkForm.title.$invalid && $v.talkForm.title.$dirty
                  }"
                  type="text"
                  placeholder="Talk title"
                  @blur="$v.talkForm.title.$touch()"
                  v-model="talkForm.title"
                />
              </p>
            </div>
            <div class="field">
              <label class="label">Description*</label>
              <p class="control">
                <input
                  class="input"
                  :class="{
                    'is-danger':$v.talkForm.description.$invalid && $v.talkForm.description.$dirty
                  }"
                  type="text"
                  placeholder="An awesome talk"
                  @blur="$v.talkForm.description.$touch()"
                  v-model="talkForm.description"
                />
              </p>
            </div>
            <div class="field">
              <label class="label">Room</label>
              <p class="control">
                <input
                  class="input"
                  :class="{
                    'is-danger':$v.talkForm.room.$invalid && $v.talkForm.room.$dirty
                  }"
                  type="text"
                  placeholder="A 41b"
                  @blur="$v.talkForm.room.$touch()"
                  v-model="talkForm.room"
                />
              </p>
            </div>
            <div class="field">
              <label class="label">Starts at*</label>
              <p class="control">
                <input
                  class="input"
                  :class="{
                    'is-danger':$v.talkForm.startsAt.$invalid && $v.talkForm.startsAt.$dirty
                  }"
                  type="text"
                  placeholder="12:00"
                  @blur="$v.talkForm.startsAt.$touch()"
                  v-model="talkForm.startsAt"
                />
              </p>
            </div>

            <div class="field is-grouped">
              <p class="control">
                <button
                  class="button"
                  :class="{'is-danger':$v.$error , 'is-info':!$v.$error}"
                  :disabled="$v.error"
                  @click.prevent="submitTalk()"
                >
                  <span v-if="!idParam">Add</span>
                  <span v-if="idParam">Update</span>
                </button>
              </p>
              <p class="control">
                <router-link to="/secure/talks" class="button is-link">Cancel</router-link>
              </p>
            </div>
          </div>
        </div>
      </div>
    </form>
  </div>

</template>

<script>
  import PageHeader from '../../shared/PageHeader.vue';
  import moment from 'moment';
  import {DEFAULT_TIME_FORMAT} from '../../../constant';
  import {formatTime} from '../../../utils';
  import {timePattern} from '../../../validators';
  import {addTalk, getTalk, updateTalk} from '../management.apollo-query';
  import {required, url, sameAs, email, minLength, maxLength} from 'vuelidate/lib/validators'
  import {withParams} from 'vuelidate'
  import SuccessModal from '../../shared/SuccessModal.vue';

  export default {
    name: 'talk-form',
    data() {
      return {
        showModalSuccess: false,
        talkForm: {
          title: '',
          description: '',
          room: '',
          startsAt: ''
        }
      }
    },
    computed: {
      idParam() {
        return this.$route.params.id;
      },
      successModalText: function () {
        const state = this.idParam ? 'updated' : 'added';
        return `The talk has successfully been ${state}`;
      }
    },
    apollo: {
      // TODO: Write getTalk
    },
    methods: {
      onClose() {
        this.showModalSuccess = false;
      },
      submitTalk() {
        const variables = {
          ...this.talkForm,
          id: this.idParam,
          startsAt: moment(this.talkForm.startsAt, DEFAULT_TIME_FORMAT).toISOString(),
        };

        // TODO: Write updateTalk and addTalk
        // Replace Promise.reject() by the correct call
        Promise.reject()
          .then(({data}) => {
            this.showModalSuccess = true;
          })
          .catch((err) => {
            console.log(err);
          });
      },
    },
    validations: {
      talkForm: {
        title: {
          required,
          minLength: minLength(3),
          maxLength: maxLength(25),
        },
        description: {
          required,
          minLength: minLength(3),
          maxLength: maxLength(200)
        },
        room: {
          minLength: minLength(3),
          maxLength: maxLength(10),
        },
        startsAt: {
          required,
          timePattern
        },
      }
    },
    components: {
      'cp-page-header': PageHeader,
      'cp-success-modal': SuccessModal
    }
  }
</script>

// angular/src/app/management/talk-form/talk-form.component.ts
import {Component, OnDestroy, OnInit} from '@angular/core';
import {FormBuilder, FormGroup, Validators} from '@angular/forms';
import {ActivatedRoute, ParamMap} from '@angular/router';
import {timeToInput, unsubscribeAll} from '../../utils';
import 'rxjs/add/operator/filter';
import {addTalk, getTalkResponse, updateTalk} from '../management.apollo-query';
import {Subscription} from 'rxjs/Subscription';
import 'rxjs/add/observable/empty';
import {Observable} from 'rxjs/Observable';

@Component({
  selector: 'cp-talk-form',
  templateUrl: './talk-form.component.html'
})
export class TalkFormComponent implements OnInit, OnDestroy {

  idParam: String;
  showModalSuccess = false;
  subscriptions: Subscription[] = [];

  talkForm: FormGroup;

  constructor(private route: ActivatedRoute,
              private fb: FormBuilder) {

    this.setupForm();
    this.getTalk = this.getTalk.bind(this);
    this.idParam = this.route.snapshot.params['id'];
  }

  ngOnInit() {
    const getTalk$ = this.route.paramMap
      .map((params: ParamMap) => params.get('id'))
      .filter((idParam: string) => !!idParam)
      .switchMap(this.getTalk)
      .subscribe(({ data }) => {
        this.updateTalkForm(data);
      });

    this.subscriptions = this.subscriptions.concat(getTalk$);
  }

  getTalk(id) {
    // TODO: Write getTalk and execute it
    return Observable.empty();
  }

  setupForm() {
    this.talkForm = this.fb.group({
      title: ['', [Validators.required, Validators.minLength(3), Validators.maxLength(50)]],
      description: ['', [Validators.required, Validators.minLength(10), Validators.maxLength(250)]],
      room: ['', [Validators.minLength(2), Validators.maxLength(20)]],
      startsAt: ['', [Validators.required, Validators.minLength(5), Validators.maxLength(5),
        Validators.pattern(/^[0-9]{2}\:[0-9]{2}$/)]],
    });
  }

  updateTalkForm(data: getTalkResponse) {
    this.talkForm.patchValue({
      ...data.talk,
      startsAt: timeToInput(data.talk.startsAt)
    });
  }


  submitTalk($event) {
    $event.preventDefault();
    const mutation = this.idParam ? updateTalk : addTalk;

    // TODO: Write updateTalk and updateTalk, execute it
    const submitTalk$ = Observable.empty().subscribe(({ data }) => {
      this.showModalSuccess = true;
    });

    this.subscriptions = this.subscriptions.concat(submitTalk$);
  }


  ngOnDestroy(): void {
    unsubscribeAll(this.subscriptions);
  }
}

<cp-page-header
  [headers]="['Talks', 'Management', 'Add|update']"
>
</cp-page-header>

<cp-success-modal
  [isVisible]="showModalSuccess"
  title="Success"
  [subTitle]=""
  [text]="'The talk has successfully been ' + (idParam ? 'updated' : 'added')"
>
</cp-success-modal>

<form
  novalidate
  [formGroup]="talkForm"
  class="section">
  <div class="container">
    <div class="columns">
      <div class="column">
        <div class="field">
          <label class="label">Title*</label>
          <p class="control">
            <input
              class="input"
              [class.is-danger]="talkForm.get('title').invalid && talkForm.get('title').dirty"
              type="text"
              placeholder="Talk title"
              formControlName="title"
              required
            />
          </p>
        </div>
        <div class="field">
          <label class="label">Description*</label>
          <p class="control">
            <input
              class="input"
              [class.is-danger]="talkForm.get('description').invalid && talkForm.get('description').dirty"
              type="text"
              placeholder="An awesome talk"
              formControlName="description"
              required
            />
          </p>
        </div>
        <div class="field">
          <label class="label">Room</label>
          <p class="control">
            <input
              class="input"
              [class.is-danger]="talkForm.get('room').invalid && talkForm.get('room').dirty"
              type="text"
              placeholder="A 41b"
              formControlName="room"
            />
          </p>
        </div>
        <div class="field">
          <label class="label">Starts at*</label>
          <p class="control">
            <input
              class="input"
              [class.is-danger]="talkForm.get('startsAt').invalid && talkForm.get('startsAt').dirty"
              type="text"
              placeholder="12:00"
              formControlName="startsAt"
              required
            />
          </p>
        </div>

        <div class="field is-grouped">
          <p class="control">

            <button
              class="button"
              [class.is-danger]="talkForm.invalid"
              [class.is-info]="talkForm.valid"
              [disabled]="talkForm.invalid"
              (click)="submitTalk($event)"
            >
              <span *ngIf="!idParam">Add</span>
              <span *ngIf="idParam">Update</span>
            </button>
          </p>
          <p class="control">
            <a routerLink="/secure/talks" class="button is-link">Cancel</a>
          </p>
        </div>
      </div>
    </div>
  </div>
</form>
