// vue-js/src/components/authentication/Login.vue
<template>
  <form class="container" novalidate>
    <div class="columns is-vcentered">
      <div class="column is-4 is-offset-4">
        <h1 class="title">
          Sign in
        </h1>
        <div class="box">
          <label class="label">Email*</label>
          <p class="control">

            <input
              class="input"
              :class="{
                'is-danger':$v.credentials.email.$invalid && $v.credentials.email.$dirty
              }"
              type="email"
              placeholder="jsmith@example.org"
              @blur="$v.credentials.email.$touch()"
              v-model="credentials.email"
              required
            />
          </p>
          <label class="label">Password*</label>
          <p class="control">
            <input
              class="input"
              :class="{
                'is-danger':$v.credentials.password.$invalid && $v.credentials.password.$dirty
              }"
              type="password"
              placeholder="●●●●●●●"
              @blur="$v.credentials.password.$touch()"
              v-model="credentials.password"
              required
            />
          </p>

          <p v-if="userNotFound">
            User not found
          </p>

          <hr/>

          <p class="control">
            <button class="button is-outlined is-large is-fullwidth"
                    @click.prevent="login()" :disabled="$v.$invalid">
              Login
            </button>
          </p>
        </div>
        <p class="has-text-centered">
          <router-link to="/authentication/register" active-class="is-active">
            Register
          </router-link>
        </p>
      </div>
    </div>
  </form>

</template>
<script>
  import {login} from './authentication.apollo-query';
  import {required, email, minLength, maxLength, between} from 'vuelidate/lib/validators'
  import auth from './authentication.service';

  export default {
    data() {
      return {
        userNotFound: false,
        publicName: '',
        credentials: {
          email: '',
          password: '',
        }
      }
    },
    validations: {
      credentials: {
        email: {
          required,
          email,
          maxLength: maxLength(50),
        },
        password: {
          required,
          maxLength: maxLength(50),
          minLength: minLength(3),
        }
      }
    },
    apollo: {},
    methods: {
      login() {
        // TODO: Write login mutation and execute it
        // Replace Promise.reject() by the correct call
        Promise.reject()
          .then(({data}) => {
            this.userNotFound = false;
            this.publicName = data.signinUser.user.publicName;
            this.storePublicNameInLocalStorage(this.publicName);
            this.navigateToHome();
          })
          .catch((error) => {
            console.log(error);
            this.userNotFound = true;
          })
      },
      storePublicNameInLocalStorage(name) {
        auth.savePublicName(name);
      },
      navigateToHome() {
        this.$router.push('/');
      }
    }
  }
</script>

// react-app/src/component/authentication/Login.js
import React, {Component} from 'react';
import {Link} from 'react-router-dom';
import {isValidForm, validateInput} from '../../utils/index';
import {gql} from 'react-apollo'; import graphql from 'react-apollo/lib/graphql'; import {SuccessModal} from '../modal/index';

class Login extends Component {
  constructor(props) {
    super(props);

    this.state = {
      validation: {},
      data: {},
      validForm: true,
      userNotFound: false,
      showSuccessModel: false
    };
  }

  handleInput = (event, defaultClass = 'input') => {
    this.setState({
      data : {
        ...this.state.data,
        [event.target.name]: event.target.value
      },
      validation: {
        ...this.state.validation,
        [event.target.name]: validateInput(event) ? defaultClass :  defaultClass + ' is-danger'
      }
    });
  };

  submitLogin = () => {
    if(isValidForm(2, this.state.validation)) {
      //TODO call the mutation function that graphql connector passed in the props
      //Pass the variables here
      this.props.callTheMutation()
        .then((re) => {
          this.setState({
            validForm : true,
            userNotFound: false,
            showSuccessModel: true
          });
        })
        .catch(err => {
          this.setState({
            userNotFound: true
          });
        })
    } else {
      this.setState({
        validForm : false
      })
    }
  };

  render() {
    const {validation} = this.state;
    return <div className="section">
      <SuccessModal
        isVisible={this.state.showSuccessModel}
        hide={() => this.setState({
          showSuccessModel : false
        })}
        title="Success"
        text="You are successfully logged in"
      />
      <div className="container">
        <div className="columns is-vcentered">
          <div className="column is-4 is-offset-4">
            <h1 className="title">
              Sign in
            </h1>
            <div className="box">
              <label className="label">Email*</label>
              <p className="control">
                <input
                  className={validation.email || 'input'}
                  type="email"
                  placeholder="jsmith@example.org"
                  name="email"
                  required
                  onChange={this.handleInput}
                />
              </p>
              <label className="label">Password*</label>
              <p className="control">
                <input
                  className={validation.password || 'input'}
                  type="password"
                  placeholder="●●●●●●●"
                  name="password"
                  required
                  onChange={this.handleInput}
                />
              </p>
              {
                this.state.userNotFound && <p>
                  User not found
                </p>
              }

              <hr/>

              <p className="control">
                <button
                  className={
                    ["button is-outlined is-large is-fullwidth"]
                      .concat(this.state.validForm ? 'is-info' : 'is-danger')
                      .join(' ')
                  }
                  onClick={this.submitLogin}
                >Login</button>
              </p>
            </div>
            <p className="has-text-centered">
              <Link to="/authentication/register">Register</Link>
            </p>
          </div>
        </div>
      </div>
    </div>;
  }
}

//TODO write a mutation to log the user in
//This is typical to graph.cool, get back the token
// But you don't have to do anything with it
// (You could store it in your local storage and use it in other requests)
const mutation = undefined;

//Use graphql connector from react-apollo to make the mutation available to your component
 const deleteThisWhenImplementing = {
   callTheMutation: () => {
     return new Promise((resolve, reject) => reject("You're not done"));
   }
 };

 //TODO connect with graphql HOC from react-apollo
const LoginData = () => <Login {...deleteThisWhenImplementing}/>  ;

export default LoginData;
