// angular/src/app/management/conference-table-list/conference-table-list.component.ts
import {Component, OnDestroy, OnInit} from '@angular/core';
import {Conference} from '../../conference/types';
import {Apollo} from 'apollo-angular';
import {deleteConference, getAllConferences, getAllConferencesResponse} from '../management.apollo-query';
import {DEFAULT_ITEMS_PER_PAGE, START_PAGE} from '../../table.config';
import {Subscription} from 'rxjs/Subscription';
import {unsubscribeAll} from '../../utils';
import {Observable} from 'rxjs/Observable';

@Component({
  selector: 'cp-conference-table-list',
  templateUrl: './conference-table-list.component.html',
  styles: []
})
export class ConferenceTableListComponent implements OnInit, OnDestroy {

  conferences: [Conference];
  amountPerPage = DEFAULT_ITEMS_PER_PAGE;
  total = 0;
  pageNumber = START_PAGE;
  subscriptions: Subscription[] = [];

  constructor(
  ) {
    this.deleteConference = this.deleteConference.bind(this);
    this.navigateToPage = this.navigateToPage.bind(this);
  }

  ngOnInit() {
    this.getConferencesChunk();
  }

  navigateToPage(pageNumber) {
    this.getConferencesChunk(pageNumber);
  }

  getConferencesChunk(pageNumber= 1) {
    this.subscriptions = this.subscriptions.concat(
      //TODO getAllConferences
      Observable.empty()
      .subscribe(({data}) => {
        this.conferences = data.conferences;
        this.total = 0//TODO;
        this.pageNumber = pageNumber;
      })
    );
  }

  deleteConference(id) {
    this.subscriptions = this.subscriptions.concat(
      //TODO call delete conference and then get all conferences
      Observable.empty()
    .subscribe(({data}) => {
      this.conferences = data.conferences;
      this.total = 0; //TODO
      this.pageNumber = 1;
    })
    );
  }

  ngOnDestroy() {
    unsubscribeAll(this.subscriptions);
  }

}

<div>
  <cp-page-header
    [headers]="['Conferences']"
  >
    <span class="title is-4 is-info is-pulled-right ">
      <a
        class="icon is-large"
        routerLink="/secure/conference"
      >
        <i class="fa fa-plus-circle"></i>
      </a>
      </span>
  </cp-page-header>

  <div class="section">
    <div class="container">
      <div class="columns">
        <div class="column">
          <cp-table
            [labels]="['ID', 'Name', 'City', 'Country', 'Start Date']"
            [amountPerPage]="amountPerPage"
            [total]="total"
            [pageNumber]="pageNumber"
            [navigateToPage]="navigateToPage"
          >
            <tr cp-conference-table-row *ngFor="let conference of conferences"
              [conference]="conference"
                [deleteConference]="deleteConference"
            >
            </tr>
          </cp-table>
        </div>
      </div>
    </div>
  </div>
</div>

// vue-js/src/components/management/conference/ConferenceTableList.vue
<template>
  <div>
    <cp-page-header
      :headers="['Conferences', 'List']">
    <span class="title is-4 is-info is-pulled-right ">
      <router-link class="icon is-large" to="/secure/conference">
                <i class="fa fa-plus-circle"></i>
      </router-link>
      </span>
    </cp-page-header>

    <div class="section">
      <div class="container">
        <div class="columns">
          <div class="column">
            <cp-table
              :labels="['ID', 'Name', 'City', 'Country', 'Start Date']"
              :amountPerPage="amountPerPage"
              :total="total"
              :pageNumber="pageNumber"
              :navigateToPage="navigateToPage"
            >
              <cp-conference-table-row v-for="conference of conferences"
                                       :conference="conference"
                                       :deleteConference="deleteConference"
                                       :key="conference.id">
              </cp-conference-table-row>
            </cp-table>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>


<script>
  import {DEFAULT_ITEMS_PER_PAGE, START_PAGE} from '../../../constant';
  import {deleteConference, getAllConferences} from '../management.apollo-query';
  import ConferenceTableRow from './ConferenceTableRow';
  import PageHeader from '../../shared/PageHeader';
  import Table from '../../shared/Table';

  export default {
    name: 'conference',
    data() {
      return {
        conferences: [],
        amountPerPage: DEFAULT_ITEMS_PER_PAGE,
        total: 0,
        pageNumber: START_PAGE,
      }
    },
    apollo: {
      // TODO: Write getAllConferences
    },
    computed: {
      skip() {
        return (this.pageNumber - 1) * this.amountPerPage;
      }
    },
    methods: {
      deleteConference(id) {
        // TODO: Write deleteConference mutation and execute it
        // Replace Promise.reject() by the correct call

        Promise.reject()
          .then(({data}) => this.refetchAllConferences(DEFAULT_ITEMS_PER_PAGE))
          .then(({data}) => {
            this.pageNumber = 1;
            this.total = data._allConferencesMeta.count;
          });
      },
      refetchAllConferences(first, skip = 0) {
        // TODO: implement a fetchMore for the queries conference
        // Replace Promise.reject() by the correct call
        return Promise.reject();
      },
      navigateToPage(pageNumber) {
        this.pageNumber = pageNumber;
      }
    },
    components: {
      'cp-page-header': PageHeader,
      'cp-table': Table,
      'cp-conference-table-row': ConferenceTableRow,
    }
  }
</script>
