// react-app/src/component/management/talks/AddTalksToConference.js
import React, {Component} from 'react';
import {compose, gql, graphql} from 'react-apollo';
import {waitForGraphql} from '../../../apollo/index'; import TalkItem from './TalkItem';

class AddTalksOnConference extends Component {

  constructor(props) {
    super(props);
  }

  addTalk = (talkId, conferenceId) => {
    //TODO call mutation
    this.props.updateConference()
      .then(_ => {
        //TODO refetch from DB again (no optimistic update strategy used here)
        this.refetch();
      })
  };

  deleteTalk = (talkId, conferenceId) => {
    //TODO call the mutation you get from graphql HOC
    //Add all needed variables (getPlannedTalks can help you)
    this.props.updateConference({
      variables: {}
    })
      .then(_ => {
        this.refetch();
      })
  };

  refetch = () => {
    //TODO use the refetch function passed on the props
  };

  getPlannedTalks = (talks, conferenceId) => {
    return talks.filter(talk => {
      return talk.conferences && talk.conferences.some(({id}) => id === conferenceId);
    });
  };

  render() {
    const {
      getTalks: {
        talks
      },
      updateConference,
      match: {
        params: {
          id: conferenceId
        }
      }
    } = this.props;

    const plannedTalks = this.getPlannedTalks(talks, conferenceId);

    return <div>
      <div className="section product-header">
        <div className="container">
          <div className="columns">
            <div className="column">
            <span className="title is-3">
              Talks
            </span>
              <span className="title is-3 has-text-muted">&nbsp;|&nbsp;</span>
              <span className="title is-4 has-text-muted">
            Management
            </span>
              <span className="title is-3 has-text-muted">&nbsp;|&nbsp;</span>
              <span className="title is-4 has-text-muted">
            Add or Remove talks on Conference
            </span>
            </div>
          </div>
        </div>
      </div>
      <div className="section">
        <div className="container">
          <div className="columns">
            <div className="column is-4 ">
              <nav className="panel">
                <p className="panel-heading">
                  Talk List
                </p>
                {
                  talks.map(talk =>
                    <TalkItem
                      key={talk.id}
                      attending={false}
                      talk={talk}
                      onClick={(talkId) =>
                        this.addTalk(talkId, conferenceId)
                      }
                    />
                  )
                }
              </nav>
            </div>
            <div className="column is-4 is-offset-2">
              <nav className="panel">
                <p className="panel-heading">
                  Conference Talks
                </p>
                {
                  plannedTalks.length > 0 ?
                    plannedTalks.map(talk =>
                      <TalkItem
                        key={talk.id}
                        attending={true}
                        talk={talk}
                        onClick={(talkId) => this.deleteTalk(talkId, conferenceId)}
                      />
                    )
                    :
                    <a className="panel-block">
                      No Talks yet on this conference
                    </a>
                }
              </nav>
            </div>
          </div>
        </div>
      </div>
    </div>
  }
}


const getTalks = gql`
    query {
        talks: allTalks {
            id
            title
            conferences {
                id
            }
        }
    }
`;

//TODO write the mutation to update a conference and add the new talks ids on it
const updateConference = undefined;

//Name you mutations, queries
const getTalksConfig = {
};

const updateConferenceConfig = {
};

//Connect all queries and mutation together
/*const AddTalksOnConferenceData = compose(
  waitForGraphql(getTalks, getTalksConfig),
  graphql(updateConference, updateConferenceConfig)
)(AddTalksOnConference);*/

export default AddTalksOnConference;

// angular/src/app/management/add-talks-to-conference/add-talks-to-conference.component.ts
import {Component, OnDestroy, OnInit} from '@angular/core';
import {Talk} from '../../talk/types';
import {Apollo} from 'apollo-angular';
import {ActivatedRoute} from '@angular/router';
import {
  getAllTalks, getAllTalksResponse, getTalksOnConference,
  getTalksOnConferenceResponse, updateTalksOnConference
} from '../management.apollo-query';
import {Subscription} from 'rxjs/Subscription';
import {unsubscribeAll} from '../../utils';

@Component({
  selector: 'cp-add-talks-to-conference',
  templateUrl: './add-talks-to-conference.component.html'
})
export class AddTalksToConference implements OnInit, OnDestroy {
  talksOnConference = [];
  talks = [];
  conferenceIdParam: string;
  subscriptions: Subscription[] = [];

  constructor(
    private apollo: Apollo,
    private route: ActivatedRoute
  ) {
    this.conferenceIdParam = this.route.snapshot.params['id'];
    this.addTalk = this.addTalk.bind(this);
    this.deleteTalk = this.deleteTalk.bind(this);
  }

  ngOnInit() {
    this.getTalksAndTalksOnConference();
  }

  getTalksAndTalksOnConference() {
    this.subscriptions = this.subscriptions.concat(
      this.apollo.query<getTalksOnConferenceResponse>({
        query: getTalksOnConference,
        fetchPolicy: 'cache-and-network'
      })
        .subscribe(({ data }) => {
          this.talks = data.talks;
          this.talksOnConference = data.talks
            .filter(talk => {
              return talk.conferences.some(conference => conference.id === this.conferenceIdParam);
            });
        })
    );
  }

  addTalk(talkId) {
    this.subscriptions = this.subscriptions.concat(
      this.apollo.mutate({
        mutation: updateTalksOnConference,
        variables: {
          conferenceId: this.conferenceIdParam,
          talkIds: this.talksOnConference
            .map(talkOnConference => talkOnConference.id)
            .concat(talkId)
        }
      })
        .subscribe(_ => {
          this.getTalksAndTalksOnConference();
        })
    );
  }

  deleteTalk(talkId) {
    this.subscriptions = this.subscriptions.concat(
      this.apollo.mutate({
        mutation: updateTalksOnConference,
        variables: {
          conferenceId: this.conferenceIdParam,
          talkIds: this.talksOnConference
            .map(talkOnConference => talkOnConference.id)
            .filter(dbTalkId => dbTalkId !== talkId)
        }
      })
        .subscribe(_ => {
          this.getTalksAndTalksOnConference();
        })
    );
  }


  ngOnDestroy(): void {
    unsubscribeAll(this.subscriptions);
  }
}


<cp-page-header
  [headers]="['Conferences', 'Management', 'Add or remove talks on conference']"
>
</cp-page-header>

<div class="section">
  <div class="container">
    <div class="columns">
      <div class="column is-4 ">
        <nav class="panel">
          <p class="panel-heading">
            Talk List
          </p>
          <cp-talk-row
            *ngFor="let talk of talks"
            [attending]="false"
            [talk]="talk"
            [onClick]="addTalk"
          >
          </cp-talk-row>

        </nav>
      </div>
      <div class="column is-4 is-offset-2">
        <nav class="panel">
          <p class="panel-heading">
            Conference Talks
          </p>
          <cp-talk-row
            *ngFor="let talk of talksOnConference"
            [attending]="true"
            [talk]="talk"
            [onClick]="deleteTalk"
          >
          </cp-talk-row>

          <a class="panel-block" *ngIf="!talksOnConference?.length">
            No talks yet on this conference
          </a>

        </nav>
      </div>
    </div>
  </div>
</div>
