// angular/src/app/shared/page-header/page-header.component.ts
import {Component, Input, OnInit} from '@angular/core';

@Component({
  selector: 'cp-page-header',
  templateUrl: './page-header.component.html',
  styles: []
})
export class PageHeaderComponent implements OnInit {
  @Input()
  headers: [string];

  @Input()
  pipe = true;

  constructor() {
  }

  ngOnInit() {
  }

}

<div class="section product-header">
  <div class="container">
    <div class="columns">
      <div class="column">

        <ng-container *ngFor="let header of headers; let i = index;">
          <ng-container *ngIf="i === 0; then mainHeader else defaultHeader">
          </ng-container>

          <ng-template #mainHeader>
            <span class="title is-3">
             {{header}}
            </span>
          </ng-template>

          <ng-template #defaultHeader>
            <span class="title is-3 has-text-muted" *ngIf="pipe">&nbsp;|&nbsp;</span>
            <span class="title is-4 has-text-muted">
               {{header}}
            </span>
          </ng-template>

        </ng-container>

        <ng-content></ng-content>

      </div>
    </div>
  </div>
</div>

// vue-js/src/components/shared/PageHeader.vue
<template>
  <div class="section product-header">
    <div class="container">
      <div class="columns">
        <div class="column">
          <template v-for="(header, index) of headers ">
             <span class="title is-3" v-if="index===0">
              {{header}}
             </span>

            <span class="title is-3 has-text-muted" v-if="index!==0 && pipe">&nbsp;|&nbsp;</span>
            <span class="title is-4 has-text-muted" v-if="index!==0 ">
               {{header}}
            </span>
          </template>
          <slot>
          </slot>
        </div>
      </div>
    </div>
  </div>
</template>

<script>

  export default {
    name: 'page-header',
    props: {
      headers: {
        type: Array,
        required: true
      },
      pipe: {
        type: Boolean,
        default: true
      },
    },
  }
</script>
