// conf-planner-angular/src/app/shared/success-modal/success-modal.component.ts
import {Component, Input} from '@angular/core';

@Component({
  selector: 'cp-success-modal',
  templateUrl: './success-modal.component.html'
})
export class SuccessModal {

  @Input()
  isVisible: boolean;

  @Input()
  title: string;

  @Input()
  subTitle: string;

  @Input()
  text: string;

  hide() {
    this.isVisible = false;
  }
}

<div
  class="modal"
  [class.is-active]="isVisible"
>
  <div class="modal-background"></div>
  <div class="modal-content">
    <div class="box">
      <article class="media">
        <div class="media-content">
          <div class="content">
            <p>
              <strong>{{title}}</strong>
              <small>{{subTitle}}</small>
              <br/>
              {{text}}
            </p>
          </div>
        </div>
      </article>
    </div>
  </div>
  <button
    class="modal-close"
    (click)="hide()"
  ></button>
</div>

// vue-js/src/components/shared/SuccessModal.vue
<template>
  <div
    class="modal"
    :class="{'is-active':isVisible}"
  >
    <div class="modal-background"></div>
    <div class="modal-content">
      <div class="box">
        <article class="media">
          <div class="media-content">
            <div class="content">
              <p>
                <strong>{{title}}</strong>
                <small>{{subTitle}}</small>
                <br/>
                {{text}}
              </p>
            </div>
          </div>
        </article>
      </div>
    </div>
    <button
      class="modal-close"
      @click="onClose()"
    ></button>
  </div>

</template>

<script>

  export default {
    name: 'success-modal',
    props: {
      isVisible: {
        type: Boolean,
        required: true
      },
      onClose: {
        type: Function,
        required: true
      },
      title: {
        type: String,
        required: true
      },
      subTitle: {
        type: String,
        required: true
      },
      text: {
        type: String,
        required: true
      },
    },
    methods: {}
  }
</script>
